In [53]:
import requests
import pandas as pd
import time

cities = {
    "Delhi": (28.6139, 77.2090),
    "Mumbai": (19.0760, 72.8777),
    "Bengaluru": (12.9716, 77.5946),
    "Hyderabad": (17.3850, 78.4867),
    "Ahmedabad": (23.0225, 72.5714),
    "Chennai": (13.0827, 80.2707),
    "Kolkata": (22.5726, 88.3639),
    "Pune": (18.5204, 73.8567),
    "Jaipur": (26.9124, 75.7873),
    "Surat": (21.1702, 72.8311),
    "Lucknow": (26.8467, 80.9462),
    "Kanpur": (26.4499, 80.3319),
    "Nagpur": (21.1458, 79.0882),
    "Indore": (22.7196, 75.8577),
    "Bhopal": (23.2599, 77.4126),
    "Patna": (25.5941, 85.1376),
    "Vadodara": (22.3072, 73.1812),
    "Ludhiana": (30.9010, 75.8573),
    "Agra": (27.1767, 78.0081),
    "Nashik": (19.9975, 73.7898),
    "Faridabad": (28.4089, 77.3178),
    "Meerut": (28.9845, 77.7064),
    "Rajkot": (22.3039, 70.8022),
    "Varanasi": (25.3176, 82.9739),
    "Srinagar": (34.0837, 74.7973),
    "Aurangabad": (19.8762, 75.3433),
    "Dhanbad": (23.7957, 86.4304),
    "Amritsar": (31.6340, 74.8723),
    "Prayagraj": (25.4358, 81.8463),
    "Ranchi": (23.3441, 85.3096),
    "Howrah": (22.5958, 88.2636),
    "Coimbatore": (11.0168, 76.9558),
    "Jabalpur": (23.1815, 79.9864),
    "Gwalior": (26.2183, 78.1828),
    "Vijayawada": (16.5062, 80.6480),
    "Jodhpur": (26.2389, 73.0243),
    "Madurai": (9.9252, 78.1198),
    "Raipur": (21.2514, 81.6296),
    "Kota": (25.2138, 75.8648),
    "Chandigarh": (30.7333, 76.7794),
    "Guwahati": (26.1445, 91.7362),
    "Bhubaneswar": (20.2961, 85.8245),
    "Thiruvananthapuram": (8.5241, 76.9366),
    "Kochi": (9.9312, 76.2673),
    "Visakhapatnam": (17.6868, 83.2185),
    "Mysuru": (12.2958, 76.6394),
    "Dehradun": (30.3165, 78.0322),
    "Noida": (28.5355, 77.3910),
    "Gurugram": (28.4595, 77.0266),
    "Navi Mumbai": (19.0330, 73.0297)
}

url = "https://archive-api.open-meteo.com/v1/archive"

start_date = "2026-01-01"
end_date = "2026-08-20"

all_data = []

for city, (latitude, longitude) in cities.items():

    print(f"Fetching {city}...")

    params = {
        "latitude": latitude,
        "longitude": longitude,
        "start_date": start_date,
        "end_date": end_date,
        "hourly": (
            "temperature_2m,"
            "dew_point_2m,"
            "relative_humidity_2m,"
            "wind_speed_10m,"
            "visibility,"
            "surface_pressure,"
            "weather_code"
        ),
        "temperature_unit": "celsius",
        "wind_speed_unit": "kmh",
        "timezone": "Asia/Kolkata"
    }

    try:

        response = requests.get(
            url,
            params=params,
            timeout=120
        )

        response.raise_for_status()

        data = response.json()

        hourly = data["hourly"]

        city_df = pd.DataFrame({
            "Date/Time": hourly["time"],
            "City": city,
            "Latitude": latitude,
            "Longitude": longitude,
            "Temp_C": hourly["temperature_2m"],
            "Dew Point Temp_C": hourly["dew_point_2m"],
            "Rel Hum_%": hourly["relative_humidity_2m"],
            "Wind Speed_km/h": hourly["wind_speed_10m"],
            "Visibility_km": [
                x / 1000 if x is not None else None
                for x in hourly["visibility"]
            ],
            "Press_kPa": [
                x / 10 if x is not None else None
                for x in hourly["surface_pressure"]
            ],
            "Weather": hourly["weather_code"]
        })

        all_data.append(city_df)

        print(f"   {len(city_df):,} rows")

    except Exception as e:

        print(f"   ERROR: {e}")

    time.sleep(1)


df = pd.concat(
    all_data,
    ignore_index=True
)

df["Date/Time"] = pd.to_datetime(df["Date/Time"])

df = df.sort_values(
    ["City", "Date/Time"]
).reset_index(drop=True)

print("\n==============================")
print("DATA EXTRACTION COMPLETED")
print("==============================")

print("Cities:", df["City"].nunique())
print("Rows:", f"{len(df):,}")

print("\nColumns:")
print(df.columns.tolist())

print("\nFirst 10 rows:")
display(df.head(10))

df.to_csv(
    "India_Weather_2026_50_Cities.csv",
    index=False
)

print("\nCSV saved successfully!")

Fetching Delhi...
   5,568 rows
Fetching Mumbai...
   5,568 rows
Fetching Bengaluru...
   5,568 rows
Fetching Hyderabad...
   5,568 rows
Fetching Ahmedabad...
   5,568 rows
Fetching Chennai...
   5,568 rows
Fetching Kolkata...
   5,568 rows
Fetching Pune...
   5,568 rows
Fetching Jaipur...
   5,568 rows
Fetching Surat...
   5,568 rows
Fetching Lucknow...
   5,568 rows
Fetching Kanpur...
   5,568 rows
Fetching Nagpur...
   5,568 rows
Fetching Indore...
   5,568 rows
Fetching Bhopal...
   5,568 rows
Fetching Patna...
   5,568 rows
Fetching Vadodara...
   5,568 rows
Fetching Ludhiana...
   5,568 rows
Fetching Agra...
   5,568 rows
Fetching Nashik...
   5,568 rows
Fetching Faridabad...
   5,568 rows
Fetching Meerut...
   5,568 rows
Fetching Rajkot...
   5,568 rows
Fetching Varanasi...
   5,568 rows
Fetching Srinagar...
   5,568 rows
Fetching Aurangabad...
   5,568 rows
Fetching Dhanbad...
   5,568 rows
Fetching Amritsar...
   5,568 rows
Fetching Prayagraj...
   5,568 rows
Fetching Ranchi...
   5,568 rows
Fetching Howrah...
   5,568 rows
Fetching Coimbatore...
   5,568 rows
Fetching Jabalpur...
   5,568 rows
Fetching Gwalior...
   5,568 rows
Fetching Vijayawada...
   5,568 rows
Fetching Jodhpur...
   5,568 rows
Fetching Madurai...
   5,568 rows
Fetching Raipur...
   5,568 rows
Fetching Kota...
   5,568 rows
Fetching Chandigarh...
   5,568 rows
Fetching Guwahati...
   5,568 rows
Fetching Bhubaneswar...
   5,568 rows
Fetching Thiruvananthapuram...
   5,568 rows
Fetching Kochi...
   5,568 rows
Fetching Visakhapatnam...
   5,568 rows
Fetching Mysuru...
   5,568 rows
Fetching Dehradun...
   5,568 rows
Fetching Noida...
   5,568 rows
Fetching Gurugram...
   5,568 rows
Fetching Navi Mumbai...
   5,568 rows

==============================
DATA EXTRACTION COMPLETED
==============================
Cities: 50
Rows: 278,400

Columns:
['Date/Time', 'City', 'Latitude', 'Longitude', 'Temp_C', 'Dew Point Temp_C', 'Rel Hum_%', 'Wind Speed_km/h', 'Visibility_km', 'Press_kPa', 'Weather']

First 10 rows:

,Date/Time,City,Latitude,Longitude,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,2026-01-01 00:00:00,Agra,27.1767,78.0081,11.2,10.4,95,9.2,None,99.28,3
1,2026-01-01 01:00:00,Agra,27.1767,78.0081,10.9,10.2,95,7.6,None,99.28,1
2,2026-01-01 02:00:00,Agra,27.1767,78.0081,10.5,9.9,96,7.4,None,99.29,0
3,2026-01-01 03:00:00,Agra,27.1767,78.0081,10.3,9.8,97,8.3,None,99.28,0
4,2026-01-01 04:00:00,Agra,27.1767,78.0081,10.0,9.7,98,8.0,None,99.27,0
5,2026-01-01 05:00:00,Agra,27.1767,78.0081,10.0,9.9,99,6.9,None,99.35,3
6,2026-01-01 06:00:00,Agra,27.1767,78.0081,10.2,10.1,100,4.2,None,99.41,3
7,2026-01-01 07:00:00,Agra,27.1767,78.0081,10.4,10.3,99,7.5,None,99.46,3
8,2026-01-01 08:00:00,Agra,27.1767,78.0081,10.9,10.5,97,7.7,None,99.54,3
9,2026-01-01 09:00:00,Agra,27.1767,78.0081,12.5,10.9,90,6.7,None,99.66,3

CSV saved successfully!

In [55]:
cities = {
    "Delhi": (28.6139, 77.2090),
    "Mumbai": (19.0760, 72.8777),
    "Bengaluru": (12.9716, 77.5946),
    "Hyderabad": (17.3850, 78.4867),
    "Ahmedabad": (23.0225, 72.5714),
    "Chennai": (13.0827, 80.2707),
    "Kolkata": (22.5726, 88.3639),
    "Pune": (18.5204, 73.8567),
    "Jaipur": (26.9124, 75.7873),
    "Surat": (21.1702, 72.8311),
    "Lucknow": (26.8467, 80.9462),
    "Kanpur": (26.4499, 80.3319),
    "Nagpur": (21.1458, 79.0882),
    "Indore": (22.7196, 75.8577),
    "Bhopal": (23.2599, 77.4126),
    "Patna": (25.5941, 85.1376),
    "Vadodara": (22.3072, 73.1812),
    "Ludhiana": (30.9000, 75.8573),
    "Agra": (27.1767, 78.0081),
    "Nashik": (19.9975, 73.7898),
    "Faridabad": (28.4089, 77.3178),
    "Meerut": (28.9845, 77.7064),
    "Rajkot": (22.3039, 70.8022),
    "Varanasi": (25.3176, 82.9739),
    "Srinagar": (34.0837, 74.7973),
    "Aurangabad": (19.8762, 75.3433),
    "Dhanbad": (23.7957, 86.4304),
    "Amritsar": (31.6340, 74.8723),
    "Prayagraj": (25.4358, 81.8463),
    "Ranchi": (23.3441, 85.3096),
    "Howrah": (22.5958, 88.2636),
    "Coimbatore": (11.0168, 76.9558),
    "Jabalpur": (23.1815, 79.9864),
    "Gwalior": (26.2183, 78.1828),
    "Vijayawada": (16.5062, 80.6480),
    "Jodhpur": (26.2389, 73.0243),
    "Madurai": (9.9252, 78.1198),
    "Raipur": (21.2514, 81.6296),
    "Kota": (25.2138, 75.8648),
    "Chandigarh": (30.7333, 76.7794),
    "Guwahati": (26.1445, 91.7362),
    "Bhubaneswar": (20.2961, 85.8245),
    "Thiruvananthapuram": (8.5241, 76.9366),
    "Kochi": (9.9312, 76.2673),
    "Visakhapatnam": (17.6868, 83.2185),
    "Mysuru": (12.2958, 76.6394),
    "Dehradun": (30.3165, 78.0322),
    "Noida": (28.5355, 77.3910),
    "Gurugram": (28.4595, 77.0266),
    "Navi Mumbai": (19.0330, 73.0297)
}

print("Total Cities:", len(cities))

Total Cities: 50

In [56]:
import requests
import pandas as pd

all_data = []

for city, (latitude, longitude) in cities.items():

    print(f"Fetching {city}...")

    params = {
        "latitude": latitude,
        "longitude": longitude,
        "current": (
            "temperature_2m,"
            "dew_point_2m,"
            "relative_humidity_2m,"
            "wind_speed_10m,"
            "visibility,"
            "surface_pressure,"
            "weather_code"
        ),
        "timezone": "Asia/Kolkata"
    }

    try:
        response = requests.get(
            "https://api.open-meteo.com/v1/forecast",
            params=params,
            timeout=30
        )

        response.raise_for_status()

        current = response.json()["current"]

        all_data.append({
            "Date/Time": current["time"],
            "City": city,
            "Latitude": latitude,
            "Longitude": longitude,
            "Temp_C": current["temperature_2m"],
            "Dew Point Temp_C": current["dew_point_2m"],
            "Rel Hum_%": current["relative_humidity_2m"],
            "Wind Speed_km/h": current["wind_speed_10m"],
            "Visibility_km": (
                current["visibility"] / 1000
                if current["visibility"] is not None
                else None
            ),
            "Press_kPa": (
                current["surface_pressure"] / 10
                if current["surface_pressure"] is not None
                else None
            ),
            "Weather": current["weather_code"]
        })

        print("   Success")

    except Exception as e:
        print(f"   ERROR: {e}")

live_df = pd.DataFrame(all_data)

print("\n==========================")
print("LIVE DATA FETCH COMPLETED")
print("==========================")
print("Rows:", len(live_df))
print("Cities:", live_df["City"].nunique())

live_df.head()

Fetching Delhi...
   Success
Fetching Mumbai...
   Success
Fetching Bengaluru...
   Success
Fetching Hyderabad...
   Success
Fetching Ahmedabad...
   Success
Fetching Chennai...
   Success
Fetching Kolkata...
   Success
Fetching Pune...
   Success
Fetching Jaipur...
   Success
Fetching Surat...
   Success
Fetching Lucknow...
   Success
Fetching Kanpur...
   Success
Fetching Nagpur...
   Success
Fetching Indore...
   Success
Fetching Bhopal...
   Success
Fetching Patna...
   Success
Fetching Vadodara...
   Success
Fetching Ludhiana...
   Success
Fetching Agra...
   Success
Fetching Nashik...
   Success
Fetching Faridabad...
   Success
Fetching Meerut...
   Success
Fetching Rajkot...
   Success
Fetching Varanasi...
   Success
Fetching Srinagar...
   Success
Fetching Aurangabad...
   Success
Fetching Dhanbad...
   Success
Fetching Amritsar...
   Success
Fetching Prayagraj...
   Success
Fetching Ranchi...
   Success
Fetching Howrah...
   Success
Fetching Coimbatore...
   Success
Fetching Jabalpur...
   Success
Fetching Gwalior...
   Success
Fetching Vijayawada...
   Success
Fetching Jodhpur...
   Success
Fetching Madurai...
   Success
Fetching Raipur...
   Success
Fetching Kota...
   Success
Fetching Chandigarh...
   Success
Fetching Guwahati...
   Success
Fetching Bhubaneswar...
   Success
Fetching Thiruvananthapuram...
   Success
Fetching Kochi...
   Success
Fetching Visakhapatnam...
   Success
Fetching Mysuru...
   Success
Fetching Dehradun...
   Success
Fetching Noida...
   Success
Fetching Gurugram...
   Success
Fetching Navi Mumbai...
   Success

==========================
LIVE DATA FETCH COMPLETED
==========================
Rows: 50
Cities: 50

,Date/Time,City,Latitude,Longitude,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,2026-08-24T10:00,Delhi,28.6139,77.2090,30.0,25.3,76,3.9,9.80,98.16,0
1,2026-08-24T10:00,Mumbai,19.0760,72.8777,28.1,24.2,79,8.3,6.62,100.89,51
2,2026-08-24T10:00,Bengaluru,12.9716,77.5946,24.4,19.1,73,17.8,16.52,91.35,3
3,2026-08-24T10:00,Hyderabad,17.3850,78.4867,23.8,22.1,90,15.2,3.10,95.31,55
4,2026-08-24T10:00,Ahmedabad,23.0225,72.5714,30.3,22.6,64,6.8,18.96,100.14,1

##Check Data

In [14]:
df.head()

,Date/Time,City,Latitude,Longitude,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,2026-01-01 00:00:00,Agra,27.1767,78.0081,11.2,10.4,95,9.2,None,99.28,3
1,2026-01-01 01:00:00,Agra,27.1767,78.0081,10.9,10.2,95,7.6,None,99.28,1
2,2026-01-01 02:00:00,Agra,27.1767,78.0081,10.5,9.9,96,7.4,None,99.29,0
3,2026-01-01 03:00:00,Agra,27.1767,78.0081,10.3,9.8,97,8.3,None,99.28,0
4,2026-01-01 04:00:00,Agra,27.1767,78.0081,10.0,9.7,98,8.0,None,99.27,0

In [58]:
df.columns

Index(['Date/Time', 'City', 'Latitude', 'Longitude', 'Temp_C',
       'Dew Point Temp_C', 'Rel Hum_%', 'Wind Speed_km/h', 'Visibility_km',
       'Press_kPa', 'Weather'],
      dtype='str')

In [59]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 278400 entries, 0 to 278399
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Date/Time         278400 non-null  datetime64[us]
 1   City              278400 non-null  str
 2   Latitude          278400 non-null  float64
 3   Longitude         278400 non-null  float64
 4   Temp_C            278400 non-null  float64
 5   Dew Point Temp_C  278400 non-null  float64
 6   Rel Hum_%         278400 non-null  int64
 7   Wind Speed_km/h   278400 non-null  float64
 8   Visibility_km     0 non-null       object
 9   Press_kPa         278400 non-null  float64
 10  Weather           278400 non-null  int64
dtypes: datetime64[us](1), float64(6), int64(2), object(1), str(1)
memory usage: 23.4+ MB

In [19]:
import requests

url = "https://historical-forecast-api.open-meteo.com/v1/forecast"

params = {
    "latitude": 20.2961,
    "longitude": 85.8245,
    "start_date": "2026-01-01",
    "end_date": "2026-01-03",
    "hourly": (
        "temperature_2m,"
        "dew_point_2m,"
        "relative_humidity_2m,"
        "wind_speed_10m,"
        "visibility,"
        "surface_pressure,"
        "weather_code"
    ),
    "timezone": "Asia/Kolkata"
}

response = requests.get(url, params=params, timeout=120)

print(response.status_code)

data_test = response.json()

print(data_test["hourly"].keys())

visibility = data_test["hourly"]["visibility"]

print(visibility[:20])

200
dict_keys(['time', 'temperature_2m', 'dew_point_2m', 'relative_humidity_2m', 'wind_speed_10m', 'visibility', 'surface_pressure', 'weather_code'])
[10160.0, 7100.0, 7100.0, 300.0, 160.0, 120.0, 120.0, 120.0, 360.0, 11780.0, 15060.0, 16280.0, 16280.0, 17360.0, 17360.0, 17360.0, 16300.0, 16300.0, 16300.0, 15100.0]

In [21]:
df_backup = df.copy()

In [22]:
import requests
import pandas as pd
import time

visibility_data = []

url = "https://historical-forecast-api.open-meteo.com/v1/forecast"

for city, (latitude, longitude) in cities.items():

    print(f"Fetching visibility: {city}...")

    params = {
        "latitude": latitude,
        "longitude": longitude,

        "start_date": "2026-01-01",
        "end_date": "2026-08-20",

        "hourly": "visibility",

        "timezone": "Asia/Kolkata"
    }

    try:
        response = requests.get(
            url,
            params=params,
            timeout=120
        )

        response.raise_for_status()

        data = response.json()

        hourly = data["hourly"]

        temp_df = pd.DataFrame({
            "Date/Time": pd.to_datetime(hourly["time"]),
            "City": city,
            "Visibility_km": [
                x / 1000 if x is not None else None
                for x in hourly["visibility"]
            ]
        })

        visibility_data.append(temp_df)

        print(f"   ✓ {len(temp_df):,} rows")

    except Exception as e:
        print(f"   ❌ Error: {e}")

    time.sleep(1)


visibility_df = pd.concat(
    visibility_data,
    ignore_index=True
)

print("\nVisibility data:")
print(visibility_df.shape)

display(visibility_df.head())

Fetching visibility: Delhi...
   ✓ 5,568 rows
Fetching visibility: Mumbai...
   ✓ 5,568 rows
Fetching visibility: Bengaluru...
   ✓ 5,568 rows
Fetching visibility: Hyderabad...
   ✓ 5,568 rows
Fetching visibility: Ahmedabad...
   ✓ 5,568 rows
Fetching visibility: Chennai...
   ✓ 5,568 rows
Fetching visibility: Kolkata...
   ✓ 5,568 rows
Fetching visibility: Pune...
   ✓ 5,568 rows
Fetching visibility: Jaipur...
   ✓ 5,568 rows
Fetching visibility: Surat...
   ✓ 5,568 rows
Fetching visibility: Lucknow...
   ✓ 5,568 rows
Fetching visibility: Kanpur...
   ✓ 5,568 rows
Fetching visibility: Nagpur...
   ✓ 5,568 rows
Fetching visibility: Indore...
   ✓ 5,568 rows
Fetching visibility: Bhopal...
   ✓ 5,568 rows
Fetching visibility: Patna...
   ✓ 5,568 rows
Fetching visibility: Vadodara...
   ✓ 5,568 rows
Fetching visibility: Ludhiana...
   ✓ 5,568 rows
Fetching visibility: Agra...
   ✓ 5,568 rows
Fetching visibility: Nashik...
   ✓ 5,568 rows
Fetching visibility: Faridabad...
   ✓ 5,568 rows
Fetching visibility: Meerut...
   ✓ 5,568 rows
Fetching visibility: Rajkot...
   ✓ 5,568 rows
Fetching visibility: Varanasi...
   ✓ 5,568 rows
Fetching visibility: Srinagar...
   ✓ 5,568 rows
Fetching visibility: Aurangabad...
   ✓ 5,568 rows
Fetching visibility: Dhanbad...
   ✓ 5,568 rows
Fetching visibility: Amritsar...
   ✓ 5,568 rows
Fetching visibility: Prayagraj...
   ✓ 5,568 rows
Fetching visibility: Ranchi...
   ✓ 5,568 rows
Fetching visibility: Howrah...
   ✓ 5,568 rows
Fetching visibility: Coimbatore...
   ✓ 5,568 rows
Fetching visibility: Jabalpur...
   ✓ 5,568 rows
Fetching visibility: Gwalior...
   ✓ 5,568 rows
Fetching visibility: Vijayawada...
   ✓ 5,568 rows
Fetching visibility: Jodhpur...
   ✓ 5,568 rows
Fetching visibility: Madurai...
   ✓ 5,568 rows
Fetching visibility: Raipur...
   ✓ 5,568 rows
Fetching visibility: Kota...
   ✓ 5,568 rows
Fetching visibility: Chandigarh...
   ✓ 5,568 rows
Fetching visibility: Guwahati...
   ✓ 5,568 rows
Fetching visibility: Bhubaneswar...
   ✓ 5,568 rows
Fetching visibility: Thiruvananthapuram...
   ✓ 5,568 rows
Fetching visibility: Kochi...
   ✓ 5,568 rows
Fetching visibility: Visakhapatnam...
   ✓ 5,568 rows
Fetching visibility: Mysuru...
   ✓ 5,568 rows
Fetching visibility: Dehradun...
   ✓ 5,568 rows
Fetching visibility: Noida...
   ✓ 5,568 rows
Fetching visibility: Gurugram...
   ✓ 5,568 rows
Fetching visibility: Navi Mumbai...
   ✓ 5,568 rows

Visibility data:
(278400, 3)

            Date/Time   City  Visibility_km
0 2026-01-01 00:00:00  Delhi           7.16
1 2026-01-01 01:00:00  Delhi           7.16
2 2026-01-01 02:00:00  Delhi           7.16
3 2026-01-01 03:00:00  Delhi           7.16
4 2026-01-01 04:00:00  Delhi           5.86

In [23]:
##drop column
df = df.drop(columns=["Visibility_km"])

In [24]:
##merge 
df = df.merge(
    visibility_df,
    on=["Date/Time", "City"],
    how="left"
)

In [26]:
df = df[
    [
        "Date/Time",
        "City",
        "Latitude",
        "Longitude",
        "Temp_C",
        "Dew Point Temp_C",
        "Rel Hum_%",
        "Wind Speed_km/h",
        "Visibility_km",
        "Press_kPa",
        "Weather"
    ]
]

In [27]:
##Final check
print(df.info())


print("\nMissing values:")
print(df.isnull().sum())


display(df.head(10))

<class 'pandas.DataFrame'>
RangeIndex: 278400 entries, 0 to 278399
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Date/Time         278400 non-null  datetime64[us]
 1   City              278400 non-null  str
 2   Latitude          278400 non-null  float64
 3   Longitude         278400 non-null  float64
 4   Temp_C            278400 non-null  float64
 5   Dew Point Temp_C  278400 non-null  float64
 6   Rel Hum_%         278400 non-null  int64
 7   Wind Speed_km/h   278400 non-null  float64
 8   Visibility_km     278400 non-null  float64
 9   Press_kPa         278400 non-null  float64
 10  Weather           278400 non-null  int64
dtypes: datetime64[us](1), float64(7), int64(2), str(1)
memory usage: 23.4 MB
None

Missing values:
Date/Time           0
City                0
Latitude            0
Longitude           0
Temp_C              0
Dew Point Temp_C    0
Rel Hum_%           0
Wind Speed_km/h     0
Visibility_km       0
Press_kPa           0
Weather             0
dtype: int64

,Date/Time,City,Latitude,Longitude,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,2026-01-01 00:00:00,Agra,27.1767,78.0081,11.2,10.4,95,9.2,7.70,99.28,3
1,2026-01-01 01:00:00,Agra,27.1767,78.0081,10.9,10.2,95,7.6,5.20,99.28,1
2,2026-01-01 02:00:00,Agra,27.1767,78.0081,10.5,9.9,96,7.4,5.20,99.29,0
3,2026-01-01 03:00:00,Agra,27.1767,78.0081,10.3,9.8,97,8.3,5.20,99.28,0
4,2026-01-01 04:00:00,Agra,27.1767,78.0081,10.0,9.7,98,8.0,5.20,99.27,0
5,2026-01-01 05:00:00,Agra,27.1767,78.0081,10.0,9.9,99,6.9,2.74,99.35,3
6,2026-01-01 06:00:00,Agra,27.1767,78.0081,10.2,10.1,100,4.2,0.48,99.41,3
7,2026-01-01 07:00:00,Agra,27.1767,78.0081,10.4,10.3,99,7.5,0.34,99.46,3
8,2026-01-01 08:00:00,Agra,27.1767,78.0081,10.9,10.5,97,7.7,5.14,99.54,3
9,2026-01-01 09:00:00,Agra,27.1767,78.0081,12.5,10.9,90,6.7,7.62,99.66,3

In [28]:
##Final csv save 
df.to_csv(
    "India_Weather_2026_50_Cities_Final.csv",
    index=False
)

print("Final CSV saved successfully!")
print("Rows:", len(df))
print("Columns:", len(df.columns))

Final CSV saved successfully!
Rows: 278400
Columns: 11

                                            Data Quality Check

In [31]:
df.isnull().sum()

Date/Time           0
City                0
Latitude            0
Longitude           0
Temp_C              0
Dew Point Temp_C    0
Rel Hum_%           0
Wind Speed_km/h     0
Visibility_km       0
Press_kPa           0
Weather             0
dtype: int64

In [32]:
##Duplicate check
duplicates = df.duplicated(
    subset=["City", "Date/Time"]
).sum()

print("Duplicate rows:", duplicates)

Duplicate rows: 0

In [33]:
##Temperature validation
print("Minimum Temperature:", df["Temp_C"].min())
print("Maximum Temperature:", df["Temp_C"].max())

Minimum Temperature: -12.4
Maximum Temperature: 45.4

In [34]:
##Outliers identify 

df[
    (df["Temp_C"] < -20) |
    (df["Temp_C"] > 55)
]

Empty DataFrame
Columns: [Date/Time, City, Latitude, Longitude, Temp_C, Dew Point Temp_C, Rel Hum_%, Wind Speed_km/h, Visibility_km, Press_kPa, Weather]
Index: []

In [35]:
##Humidity validation
df[
    (df["Rel Hum_%"] < 0) |
    (df["Rel Hum_%"] > 100)
]

Empty DataFrame
Columns: [Date/Time, City, Latitude, Longitude, Temp_C, Dew Point Temp_C, Rel Hum_%, Wind Speed_km/h, Visibility_km, Press_kPa, Weather]
Index: []

In [36]:
##Wind validation
df[df["Wind Speed_km/h"] < 0]

Empty DataFrame
Columns: [Date/Time, City, Latitude, Longitude, Temp_C, Dew Point Temp_C, Rel Hum_%, Wind Speed_km/h, Visibility_km, Press_kPa, Weather]
Index: []

In [39]:
##Visibility validation
print(df["Visibility_km"].describe().round(2))

count    278400.00
mean         18.57
std           8.85
min           0.06
25%          11.70
50%          19.28
75%          25.60
max          57.08
Name: Visibility_km, dtype: float64

In [42]:
##Pressure validation
print(df["Press_kPa"].describe().round(2))

count    278400.00
mean         97.76
std           3.15
min          83.11
25%          96.12
50%          98.46
75%         100.07
max         102.20
Name: Press_kPa, dtype: float64

In [43]:
##Weather code check
print(
    sorted(df["Weather"].unique())
)

[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(51), np.int64(53), np.int64(55), np.int64(61), np.int64(63), np.int64(65), np.int64(71), np.int64(73), np.int64(75)]

In [44]:
# Wheather_map  name column create

weather_map = {
    0: "Clear Sky",
    1: "Mainly Clear",
    2: "Partly Cloudy",
    3: "Overcast",
    51: "Light Drizzle",
    53: "Moderate Drizzle",
    55: "Dense Drizzle",
    61: "Slight Rain",
    63: "Moderate Rain",
    65: "Heavy Rain",
    71: "Slight Snow",
    73: "Moderate Snow",
    75: "Heavy Snow"
}

df["Weather_Name"] = df["Weather"].map(weather_map)

In [45]:
##check
df[["Weather", "Weather_Name"]].drop_duplicates().sort_values("Weather")

        Weather      Weather_Name
2             0         Clear Sky
1             1      Mainly Clear
23            2     Partly Cloudy
0             3          Overcast
16           51     Light Drizzle
14           53  Moderate Drizzle
644          55     Dense Drizzle
751          61       Slight Rain
635          63     Moderate Rain
642          65        Heavy Rain
239433       71       Slight Snow
239429       73     Moderate Snow
239517       75        Heavy Snow

In [47]:
print(df["Weather_Name"].isnull().sum())

0

In [48]:
##Final CSV save
df.to_csv(
    "India_Weather_2026_50_Cities_Final.csv",
    index=False
)


print("CSV saved successfully!")
print("Rows:", len(df))
print("Columns:", len(df.columns))

CSV saved successfully!
Rows: 278400
Columns: 12

##Final Verificatio

In [49]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 278400 entries, 0 to 278399
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Date/Time         278400 non-null  datetime64[us]
 1   City              278400 non-null  str
 2   Latitude          278400 non-null  float64
 3   Longitude         278400 non-null  float64
 4   Temp_C            278400 non-null  float64
 5   Dew Point Temp_C  278400 non-null  float64
 6   Rel Hum_%         278400 non-null  int64
 7   Wind Speed_km/h   278400 non-null  float64
 8   Visibility_km     278400 non-null  float64
 9   Press_kPa         278400 non-null  float64
 10  Weather           278400 non-null  int64
 11  Weather_Name      278400 non-null  str
dtypes: datetime64[us](1), float64(7), int64(2), str(2)
memory usage: 25.5 MB

In [52]:
df.head()

,Date/Time,City,Latitude,Longitude,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather,Weather_Name
0,2026-01-01 00:00:00,Agra,27.1767,78.0081,11.2,10.4,95,9.2,7.7,99.28,3,Overcast
1,2026-01-01 01:00:00,Agra,27.1767,78.0081,10.9,10.2,95,7.6,5.2,99.28,1,Mainly Clear
2,2026-01-01 02:00:00,Agra,27.1767,78.0081,10.5,9.9,96,7.4,5.2,99.29,0,Clear Sky
3,2026-01-01 03:00:00,Agra,27.1767,78.0081,10.3,9.8,97,8.3,5.2,99.28,0,Clear Sky
4,2026-01-01 04:00:00,Agra,27.1767,78.0081,10.0,9.7,98,8.0,5.2,99.27,0,Clear Sky